package hr.javafx.controller;

import hr.javafx.restaurant.model.*;
import hr.javafx.restaurant.repository.*;
import javafx.fxml.FXML;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextField;

public class RestaurantAddController {
    @FXML
    private TextField restaurantTextFieldName;

    @FXML
    private ComboBox<Address> restaurantComboBoxAddress;

    @FXML
    private ComboBox<Meal> restaurantComboBoxMeals;

    @FXML
    private ComboBox<Chef> restaurantComboBoxChefs;

    @FXML
    private ComboBox<Waiter> restaurantComboBoxWaiters;

    @FXML
    private ComboBox<Deliverer> restaurantComboBoxDeliverers;

    private ContractRepository<Contract> contractRepository = new ContractRepository<>();
    private CategoryRepository<Category> categoryRepository = new CategoryRepository<>();
    private AddressRepository<Address> addressRepository;
    private MealsRepository<Meal> mealsRepository;
    private ChefRepository<Chef> chefRepository;
    private WaiterRepository<Waiter> waiterRepository;
    private DelivererRepository<Deliverer> delivererRepository;
    private RestaurantRepository<Restaurant> restaurantRepository;

    public RestaurantAddController() {
        this.addressRepository = new AddressRepository<>();
        this.mealsRepository = new MealsRepository<>(categoryRepository);
        this.chefRepository = new ChefRepository<>(contractRepository);
        this.waiterRepository = new WaiterRepository<>(contractRepository);
        this.delivererRepository = new DelivererRepository<>(contractRepository);
        this.restaurantRepository = new RestaurantRepository<>(addressRepository,
                mealsRepository, chefRepository, waiterRepository, delivererRepository);
    }

    public void initialize(){
        restaurantComboBoxAddress.getItems().addAll(addressRepository.findAll());
        restaurantComboBoxMeals.getItems().addAll(mealsRepository.findAll());
        restaurantComboBoxChefs.getItems().addAll(chefRepository.findAll());
        restaurantComboBoxWaiters.getItems().addAll(waiterRepository.findAll());
        restaurantComboBoxDeliverers.getItems().addAll(delivererRepository.findAll());
    }

   public void addNewRestaurant(){
       String restaurantName = restaurantTextFieldName.getText();
       Address selectedAddress = restaurantComboBoxAddress.getValue();
       //Set<Meal> selectedMeals = new HashSet<>(restaurantComboBoxMeals.getSelectionModel().getSelectedItems());
       //Set<Chef> selectedChefs = new HashSet<>(restaurantComboBoxChefs.getSelectionModel().getSelectedItems());
       //Set<Waiter> selectedWaiters = new HashSet<>(restaurantComboBoxWaiters.getSelectionModel().getSelectedItems());
       //Set<Deliverer> selectedDeliverers = new HashSet<>(restaurantComboBoxDeliverers.getSelectionModel().getSelectedItems());

       //Restaurant newRestaurant = new Restaurant(
               //null, // ID will be generated by the repository
              // restaurantName,
               //selectedAddress,
               //selectedMeals,
               //selectedChefs,
               //selectedWaiters,
               //selectedDeliverers
       //);

       //restaurantRepository.save(newRestaurant);

   }
}
